[package]
name = "reboot-force"
version = "1.0.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
