name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Build
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-gnu/release/reboot-force.exe
          body: |
            Emergency Windows shutdown utility (3.5 KB)

            **Usage**: Run from elevated command prompt
            **Warning**: Immediately shuts down without saving
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
